# 构建参数
ARG LITELLM_BUILD_IMAGE=python:3.11.8-slim
ARG LITELLM_RUNTIME_IMAGE=python:3.11.8-slim

# 构建阶段
FROM ${LITELLM_BUILD_IMAGE} AS builder

# 设置工作目录
WORKDIR /app

# 设置中国镜像源
RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# 安装构建依赖
RUN apt-get clean && apt-get update && \
    apt-get install -y gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install build

# 复制所有源代码
COPY . .

# 构建 Admin UI（只构建一次）
RUN chmod +x docker/build_admin_ui.sh && ./docker/build_admin_ui.sh

# 构建包
RUN rm -rf dist/* && python -m build && \
    pip install dist/*.whl

# 安装依赖为 wheels
RUN pip wheel --no-cache-dir --wheel-dir=/wheels/ -r requirements.txt

# 安装特定版本依赖
RUN pip install redisvl==0.0.7 --no-deps && \
    pip uninstall jwt PyJWT -y && \
    pip install PyJWT==2.9.0 --no-cache-dir

# 运行阶段
FROM ${LITELLM_RUNTIME_IMAGE} AS runtime

ENV NPM_CONFIG_REGISTRY=https://registry.npmmirror.com

# 更新依赖并清理
RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
    apt-get update && apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/* && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app

# 只复制必要的文件
COPY --from=builder /app/dist/*.whl .
COPY --from=builder /wheels/ /wheels/
COPY --from=builder /app/litellm/proxy/_experimental/out /app/ui/dist
COPY schema.prisma .

# 安装依赖和构建的包
RUN pip install *.whl /wheels/* --no-index --find-links=/wheels/ && \
    rm -f *.whl && \
    rm -rf /wheels

# 生成 Prisma 客户端并清理
RUN prisma generate && \
    rm -rf /root/.cache/prisma && \
    rm -rf /root/.npm && \
    rm -rf /root/.cache/node && \
    rm -rf /usr/local/lib/node* && \
    rm -rf /usr/local/include/node* && \
    rm -rf /usr/local/bin/node* && \
    rm -rf /usr/local/bin/npm* && \
    rm -rf /tmp/npm* && \
    rm -rf /root/.node-gyp

EXPOSE 4000/tcp

ENTRYPOINT ["litellm"]
CMD ["--port", "4000"]