version: "3.3"
services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile.wuban_micro
      args:
        LITELLM_BUILD_IMAGE: arm64v8/python:3.11-slim-bullseye
        LITELLM_RUNTIME_IMAGE: arm64v8/python:3.11-slim-bullseye
      platforms: linux/arm64/v8
    ports:
      - "4000:4000"
    volumes:
      - ./lite_config.yaml:/app/lite_config.yaml
      - sqlite_data:/app/sqlite
    environment:
      DATABASE_URL: "file:/app/sqlite/litellm.db"
      STORE_MODEL_IN_DB: "True"
      WUBAN_RPC_URL: "http://host.docker.internal:8080/jsonrpc"
    env_file:
      - .env
    command: ["--config", "/app/lite_config.yaml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wuban_network

volumes:
  sqlite_data:
    driver: local
networks:
  wuban_network:
    driver: bridge