version: "3.3"
services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LITELLM_BUILD_IMAGE: python:3.11.8-slim
        LITELLM_RUNTIME_IMAGE: python:3.11.8-slim
    ports:
      - "4000:4000"
    volumes:
      - ./lite_config.yaml:/app/lite_config.yaml
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    command: ["--config", "/app/lite_config.yaml"]
    depends_on:
      - db
 
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local