model_list:
  - model_name: deepseek/deepseek/deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: sk-354c3ec4f73542f681d15f2369d9fa95
      capabilities: ["text"]
  - model_name: deepseek/deepseek/deepseek-code
    litellm_params:
      model: deepseek/deepseek-code-test
      api_key: sk-354c3ec4f73542f681d15f2369d9fa95
      capabilities: ["text"]
litellm_settings:
  drop_params: True
  num_retries: 5
  request_timeout: 30
  telemetry: False
  default_headers:
    "Content-Type": "application/json"

router_settings:
  routing_strategy: simple-shuffle
  enable_pre_call_checks: false
  retry_on_failure: true
  timeout: 30

general_settings:
  master_key: sk-1234
  store_model_in_db: True
  fallback_strategy: "retry"
  port: 4000
  ui_path: "/chat/ui"